files_a: &a
    - Django

files_b: &b
    - *a
    - Unix

main:
    include: [ ]
    exclude: [ CSS ]
    private:
    template: default

test:
    include: [ *a, *b, Perl ]
    exclude: [ ]
    template: default
